### ISSUE TITLE
Misleading name (Fire Chat)?

### ISSUE THREAD

**Issue by ghost** [AlexKang/blue-chat#7]
Really awesome to see the updates to this app! As you may know, there is an app that functions similar to this one also called [FireChat](https://play.google.com/store/apps/details?id=com.opengarden.firechat). I think this app deserves its own name with its own identity. Do you think that would be a better idea?

We can brainstorm some names:

Ice Chat
Libre FireChat (kidding)

**Comment by AlexKang** [comment]
Oh I actually made this app to learn the Android bluetooth api calls so I pretty much based it off of FireChat. I'm no longer active on this project so feel free to do what you want with it!
